### ISSUE TITLE
LG L90 D415 (North American Variant) Cellular Modem Does Not Work

### ISSUE THREAD

**Issue by Osndok** [ubports/devices.ubports.com#6]
I realized only after spending a lot of time (and probably too much money) that the W7 listed on the ubports page is probably NOT the American version of the LG L90 (d415), but probably the d405 or d410...

In short, I am unable to get the cellular radio to work when applied to the firmware 10c bootstack, and am a bit nervous to try some of the later firmwares as they might perma-lock the bootloader and thus make the entire investment (heretofore) a total-loss.

Do you have any helpful insights to this? Perhaps the model number be documented on the device page?

**Comment by peat-psuwit** [comment]
Hello,
In theory, my port should work on any variant of LG L90, as supported by the official CM11 build. I even once had a confirmation from a user that it works on D415.
Anyway, there is also a recent report from another user that radio on D415 isn't working. This is pretty recent (3 months ago), so I'm guessing there's some changes in Ubuntu side.
I want you to do a few things to tackle this problem:
* I need a debug log from a component in your phone
  * Enable developer mode in Settings > About
  * Connect the phone to the computer.
  * Now, on the computer, run `adb shell` and then type the following command:
```
sudo mount -o remount,rw /
sed -i 's/ ofonod / ofonod -d ' /etc/init/ofono.override
```
Exit the shell, then reboot the phone.
  * Let the phone finish booting, then run `adb pull /var/log/syslog`. Give me syslog file.
* As you mentioned bootstack, it's worth noting that my rom is Kitkat-based, and need Kitkat-based bootstack to run properly. I can't remember what version is 10c, but I think it's Kitkat-based one because otherwise it probably won't boot. Anyway, it's worth rechecking about that.

Currently, I may not have much time as the university is open in Thailand. So, please excuse me if my response is a bit slow.

Thank you.

**Comment by Osndok** [comment]
Thanks for the help, man! In addition to attaching the requested log file, I thought I would add (1) the fact that I am using an MVNO [Ting], and (2) a distilled version of the log in case it saves you some time:

```
ofonod[2084]: gril/grilreply.c:g_ril_reply_parse_sim_status() processing app[0]
ofonod[2084]: gril/grilreply.c:g_ril_reply_parse_sim_status() processing app[1]
ofonod[2084]: parcel_r_string: parcel is too small
ofonod[2084]: gril/grilreply.c:g_ril_reply_parse_sim_status() processing app[2]
ofonod[2084]: sim_status_cb: Cannot parse SIM status reply
...
ofonod[2084]: gril/gril.c:handle_unsol_req() RIL Event slot 0: <unknown event>
```

The full and complete log file: [syslog.txt](https://github.com/ubports/devices.ubports.com/files/447835/syslog.txt)

Concerning firmware versions 10c & 10e are 4.4.2, and that 20b & 20c are 5.0.2 as per https://support.t-mobile.com/docs/DOC-30131

Furthermore, in trying to understand the timeline around all the XDA forum posts, I *think* that 10e locked out nearly all the fastboot commands which the ubuntu-flash-device utility uses.

**Comment by peat-psuwit** [comment]
I guess we have to go to another level of tracing. Use `adb shell` to run:
```
sudo mount -o remount,rw /
printf "\nenv OFONO_RIL_TRACE=1\nenv OFONO_RIL_HEX_TRACE=1\n" |sudo tee -a /etc/init/ofono.override
```
Then reboot and give me syslog again.

The text you've given indicates that oFono have some trouble parsing the response from Android's RILD. I'll have to see what is going on on the wire. Beware that, this time, the log can be quite big. You may want to filter only oFono's message.

**Comment by Osndok** [comment]
Alright, here you go! I'm not going to try and guess what you are looking for this time. :-)

I have applied this filter: `egrep -i '(ofono|ril)' syslog | cut -f5- -d' '`

[syslog_round2_filtered.txt](https://github.com/ubports/devices.ubports.com/files/447965/syslog_round2_filtered.txt)

**Comment by peat-psuwit** [comment]
OK, I now understand the problem.

On the communication socket between oFono and RILD, there is one command that has invalid record size for the list. (If you know it, it's the SIM app.) After checking with my phone, it turns out that this issue probably affects all versions of LG L90. But the reason it does work most of the time is, in most cases, there is only one entry on the SIM card. The reason it breaks in your case is there's 3 of them on your SIM card. Maybe it's related to the fact that you use an MVNO.

As the part of RILD that sends this message is closed-source, I have to fix this in oFono side. It may takes a bit more time to actually code the fix, and it'll have some delay because my free time is not that much.

**Comment by Osndok** [comment]
That sounds quite plausible. Do you think it would it help if I file a bug report here:
* https://bugs.launchpad.net/ubuntu/+source/ofono

...or is this really "specific to the L90"?

**Comment by peat-psuwit** [comment]
That's not needed. This problem is probably shared among all QCOM devices that use the same version of RILD. Filing a bug report won't help speeding up, as Ubuntu devs probably don't have those devices.

**Comment by peat-psuwit** [comment]
Turns out the fix is easier than I though. Could you please try this version of oFono?
https://launchpad.net/~peat-new/+archive/ubuntu/lg-d410-custom-test/+files/ofono_1.17.bzr6921+15.04.20160819.6-0ubuntu1peat2_armhf.deb
Give me syslog with the same filter you used.

**Comment by Osndok** [comment]
Well... it's definitely a step forward! The UI now properly shows that a sim card has been installed, but remains in "searching" mode... never finding the network.

Syslog: 
[syslog_round3_filtered.txt](https://github.com/ubports/devices.ubports.com/files/452296/syslog_round3_filtered.txt)

**Comment by peat-psuwit** [comment]
Hello,

I'm not sure if you're still interested in Ubuntu Touch, but I want you to test this version of oFono if it makes cellular work. If all goes well, I'll put this version into the image.
https://launchpad.net/~peat-new/+archive/ubuntu/lg-d410-custom-test/+files/ofono_1.17.bzr6921+15.04.20160819.6-0ubuntu1peat7_armhf.deb

**Comment by Osndok** [comment]
I'll see if I can load it up on the phone tomorrow, and let you know how it goes.

**Comment by Osndok** [comment]
I'm sorry to report that the issue still exists.

First, I flashed a fresh w7-stable-16, and confirmed that the 'no sim present' message appears (though a sim card is in the device).

Then, I installed the custom build you specified, and found that the notification area said that the cellular network was forever 'searching'.

Finally, I acquired the syslog output, as before, and provide it here:
[syslog_round4_filtered.txt](https://github.com/ubports/devices.ubports.com/files/695550/syslog_round4_filtered.txt)

**Comment by peat-psuwit** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate further why one still can't have phone register with the network.](https://trello.com/c/HJLwIZhK/23-investigate-further-why-one-still-can-t-have-phone-register-with-the-network)

**Comment by peat-psuwit** [comment]
I'm sorry to hear that. I want you to give me more clue:

1. I want you to give the syslog after a restart. And also give me the radio logcat.
A radio logcat can be grabbed by running `/system/bin/logcat -d -b radio >logcat-radio.log`
2. I want a radio logcat on Android too, to find out what Android does on this network.

Thank you.

**Comment by Osndok** [comment]
Well... I finally got around to putting Android back on it (which was not particularly easy, for me), and I found that CM does not handle this case either. It shows both the mvno and parent carrier in the carrier screen, and tapping on the mvno causes it to deep think for a few minutes before giving up and saying something like "not allowed".

I do seem to recall it working with the stock rom, but given my previous experience with the windows tools and bootloader locking... and that they might not even be using ofono... I'm not sure I want to venture into the "official rom" side of things right now.

So given the doubtable permission message (as I suppose there is a greater chance that imei/esid got blacklisted than "all mvnos are broken in CM"), and my waning interest in this phone... I think I'll just let it broken and move on. :(
